remote_theme: pages-themes/modernist@v0.2.0
Title: Bartlomiej Zabek CV
print(Bartlomiej Zabek CV
Jestem absolwentem Technikum elektryczno-mechanicznego o profilu
Teleinformatyk. W tym roku rozpoczynam dalszą edukację na uczelni:
Akademia Górniczo-Hutnicza w Krakowie o profilu Cyberbezpieczeństwo.
Jestem osobą bardzo dobrze radzącą sobie w zespole. Szybko się uczę i
jestem bardzo pracowity. Dotychczas pracowałem w firmie moich
rodziców jednak chciałbym spróbować wykorzystać umiejętności w
branży IT.)
